Friendship and User Associations
ZawadiSumba66/ror-social-scaffold pull request #2
Opened 2021-03-05 15:26 UTC by ZawadiSumba66

In this milestone, we created associations between the user and the friendship models.  We also integrated RSpec for the user, post, comment, like, and friendship model

2021-03-05 19:18 UTC, lekegitrepo requested changes
## Status: Changes Required! :recycle:
### Hi @ZawadiSumba66 and @SamArsanios :clap: :clap:
#### Well done :muscle: The project looks great. However, some requirements are missing/not implemented correctly. Check my comments below :point_down:

#### 1) Readme:
 - Add how to clone the project to the "Getting Started" section.

#### 2) App Behaviour:
 - User should be able to invite a friend: there should be an invitation button next to the usernames in the "ALL USERS" page and likewise in each user profile page.
 - User should also be able to see the accept and reject buttons if another send a friend request to them
 - Posts timeline should include posts written by logged-in user and their friends

#### 3) Test:
 - One test is failing.
 - Add integration tests.

#### _Reviewed by Temitayo Adeleke_

2021-03-08 17:52 UTC, acushlakoncept requested changes
# Status: Changes Required ♻️

### Excellent job so far, most requirements are working well. 👍 

There are still some changes that are necessary for this project to be approved.

- [ ] Your posts timeline should include posts written by logged-in user and their friends ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friends_timeline.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))

- [ ] One of your tests are failing, kindly add integration tests.
<img width="1009" alt="Screen Shot 2021-03-08 at 6 41 43 PM" src="https://user-images.githubusercontent.com/5264771/110360157-a8029000-803e-11eb-9a8d-0e6e31e3f7d0.png">

- [ ] Kindly add Integration tests, great job on the unit testing, you should consider using [shoulda-matchers ](https://github.com/thoughtbot/shoulda-matchers) for your unit test, It is simple and expressive, you should try it.  Example
```
describe 'associations' do
    it { should belong_to(:category) }
  end

  describe 'validations' do
    it { should validate_presence_of(:name) }
    it { should validate_uniqueness_of(:name).scoped_to(:category_id) }
  end
```

- [ ] There should be absolutely NO logic in views. Views are only for displaying information that became available to it from its corresponding controller not generating it.  
See affected files below:
> `layouts/application.html.erb`

**Don't know where to start or how to?** See  [Rails View Helpers Best Practices](https://medium.com/@acushla4real/rails-view-helpers-best-practices-guide-d7d7b6db3db4) 


### Cheers and Happy coding! 💻 👏

(Feel free to contact me on slack(@acushla) or reply to this thread, if you have any additional question)
Uduak Essien
[Twitter](https://twitter.com/acushlakoncept) | [LinkedIn](https://www.linkedin.com/in/acushlakoncept/)

2021-03-09 12:39 UTC, acushlakoncept requested changes
# Status: Changes Required ♻️

### I am truly impressed with your progress, well done 👍 
Let us quickly add some finishing touches and request another review.

- [ ] You're yet to take care of the failed tests
<img width="1009" alt="Screen Shot 2021-03-09 at 1 32 32 PM" src="https://user-images.githubusercontent.com/5264771/110471043-ec903900-80db-11eb-9ca3-d0ed0ba5bd4e.png">

- [ ] Use this time to organize your specs, combining both unit and integration tests in one file is not a good practice. See the comments I have made on your codebase.

### Do this and we should be good to go.

### Cheers and Happy coding! 💻 👏

(Feel free to contact me on slack(@acushla) or reply to this thread, if you have any additional question)
Uduak Essien
[Twitter](https://twitter.com/acushlakoncept) | [LinkedIn](https://www.linkedin.com/in/acushlakoncept/)

2021-03-09 12:39 UTC, acushlakoncept commented on spec/models/user_spec.rb
> +  end
It's not a good practice to combine unit and integration tests in one file. This should go to another file, say `spec/feature/user_spec.rb`

2021-03-09 13:52 UTC, mahmoud717 approved these changes
### STATUS: APPROVED ✔️ ✔️ 

**hi @ZawadiSumba66**

**Great job with making all of the requirements. the project is approved, you can go ahead and merge this pull request**

2021-03-11 09:12 UTC, merged